config/routes.rb
Crowdfunder::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  root to: 'welcome#index'

  resources :projects do
    resources :breakpoints
  end

  resources :pledges, :only => [:create]

  resources :users

  resources :sessions

end

app/models/breakpoint.rb
class Breakpoint < ActiveRecord::Base
	belongs_to :project
	has_many :pledges
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	belongs_to :user
	belongs_to :breakpoint
	
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :breakpoints

	belongs_to :owner, class_name: "User", foreign_key: 'user_id'


	def pledged
		result = 0

		breakpoints.each do |breakpoint|
			result += breakpoint.pledges.count * breakpoint.pledge_amt
		end
		
		result
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :projects
  has_many :pledges

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

	def ensure_logged_in
		unless current_user
			flash[:alert] = "Please log in"
			redirect_to new_session_path
		end
	end
end

app/controllers/breakpoints_controller.rb
class BreakpointsController < ApplicationController
  before_filter :load_project

  def new
  	@breakpoint = Breakpoint.new
  end

  def create
  	@breakpoint = @project.breakpoints.build(breakpoint_params)

  	if @breakpoint.save
  		redirect_to project_path(@project), :notice => "Pledge completed!"
  	else
  		render "new"
  	end

  end

  def edit
  	@breakpoint = Breakpoint.find(params[:id])
  end

  def update
  	@breakpoint = Breakpoint.find(params[:id])

  	if @breakpoint.update_attributes(breakpoint_params)
  		redirect_to project_path(@project), :notice => "Updated!"
  	else
  		render :edit
  	end

  end

  def destroy
  	@breakpoint = Breakpoint.find(params[:id])
  	@breakpoint.destroy
  	redirect_to project_path
  end

  private

  def load_project
    @project = Project.find(params[:project_id])
  end

  def breakpoint_params
  	params.require(:breakpoint).permit(:pledge_amt, :description, :delivery)

  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	before_filter :ensure_logged_in

	def create
		# params[:pledge]
		#				[:breakpoint_id]

		p = Pledge.new( pledge_params )
		p.user = current_user

		if p.save

			project = p.breakpoint.project
			respond_to do |format|
				format.html { redirect_to project_path( project ), :notice => "YOU MADE A PLEDGE!" }
				format.json { render json: { pledged: project.pledged} }
			end
		else
			respond_to do |format|
				format.html { render 'projects/index' }
				format.json { }
			end
		end
	end

	private
	def pledge_params
		params.require(:pledge).permit(:breakpoint_id)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :load_project, :only => [:show, :edit, :update, :destroy]
	before_filter :ensure_ownership, :except => [:index, :show, :new, :create]
	before_filter :ensure_logged_in, :except => [:index, :show]


	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		@project.owner = current_user
		if @project.save
			redirect_to projects_url
		else
			render :new
		end
	end

	def show
		@pledge = Pledge.new
	end

	def edit
	end

	def update

		if @project.update_attributes(project_params)
			redirect_to project_path(@project)
		else
			render :edit
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	private

	def load_project
		@project = Project.find(params[:id])
	end

	def ensure_ownership
		unless current_user == @project.owner
			flash[:alert] = "You have invalid access to this project!"
			redirect_to projects_path
		end
	end

	def project_params
		params.require(:project).permit(:title, :category, :image, :goal, :description, :pledged, :start_time, :end_time, :user_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		if @user = login(params[:email], params[:password])
			redirect_back_or_to root_url, :notice => "Login successful!"
		else
			flash.now[:alert] = "Invaild email or password"
			render action: "new"
		end
	end

	def destroy
		logout
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, :notice => "Signed Up!"
		else
			render "new"
		end

	end

private

def user_params
	params.require(:user).permit(:username, :email, :password, :password_confirmation, :first_name, :last_name)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breakpoints_helper.rb
module BreakpointsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/breakpoints/_form.html.erb
<%= form_for([@project, @breakpoint]) do |f| %>
	<div class="field">
		<%= f.label :pledge_amt %>
		<%= f.number_field :pledge_amt %>
	</div>

	<div class="field">
		<%= f.label :decription %>
		<%= f.text_area :description %>
	</div>

	<div class="field">
		<%= f.label :delivery %>
		<%= f.text_field :delivery %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/breakpoints/edit.html.erb
<h1>Breakpoints#edit</h1>
<p>Find me in app/views/breakpoints/edit.html.erb</p>

app/views/breakpoints/new.html.erb
<h1>Add Pledges</h1>
<%= render 'form' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "home", root_url, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if current_user %>
            <font color="white"> Signed in as <%= current_user.email %> | <%= link_to "Log out", session_path("current"), :method => :delete  %></font>
          <% else %>
            <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
          <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%= render 'layouts/header' %>
	</header>

	<div id="flash">
		<% if flash[:notice] %>
			<p id="notice"><%= flash[:notice] %></p>
		<% end %>
		<% if flash[:alert] %>
			<p id="alert"><%= flash[:alert] %></p>
		<% end %>
	</div>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.text_field :image %>
	</div>

	<div class="field">
		<%= f.label :category %>
		<%= f.text_field :category %>
	</div>

	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>

	<div class="field">
		<%= f.label :goal %>
		<%= f.text_field :goal %>
	</div>

	<div class="field">
		<%= f.label :end_time, "End on date & time" %>
		<%= f.date_field :end_time %>
	</div>

	<div class="action">
		<%= f.submit %>
	</div>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit your project</h1>
<%= link_to "Back to home", root_url %>
<%= render 'form' %>

<%= link_to "Add breakpoints", new_project_breakpoint_path(@project) %>

<%= link_to "Don't want it", project_path(@project), method: :delete, data: { confirm: 'Are you sure you wanna stop working on this?' } %>

app/views/projects/index.html.erb
<%= link_to "Back to home", root_url %>
<h1>Check out these cool projects!</h1>

<% @projects.each do |project| %>
	<%= image_tag project.image %><br/>
	<%= link_to project.title, "/projects/#{project.id}" %><br />
	Description: <%= project.description %><br />
	Goal: <%= number_to_currency(project.goal) %><br/>
	Ends on: <%= project.end_time %><br/>
<% end %>

app/views/projects/new.html.erb
<h1>Meet your new project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= link_to "Back to home", root_url %> | <%= link_to "Edit Project", edit_project_path %>
<h1><%= @project.title %></h1>

<p><%= image_tag @project.image%></p>
<p>Description: <%= @project.description %></p>
<p>Goal: $<%= @project.goal %></p>
<p>Pledged: $<span id="pledged_amt"><%= @project.pledged %></span></p>
<p></p>

<h3>Rewards!</h3>

<% @project.breakpoints.each do |breakpoint| %>
	<div class="breakpoint">
		Pledge: <%= breakpoint.pledge_amt %><br>
		Description: <%= breakpoint.description %><br>
		Estimated Delivery: <%= breakpoint.delivery %><br>

<!-- 		
		<%= link_to "poop", pledges_path( :breakpoint_id => breakpoint.id, :poop => 'poop' ), :method => "POST" %>
 -->

		<%= form_for @pledge do |f| %>
			<%= f.hidden_field :breakpoint_id, { :value => breakpoint.id } %>
			<%= f.submit "Pledge!" %>
		<% end %>
	
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign-up Here!</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


	<div class="field">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</div>

	<div class="field">
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</div>

	<div class="field">
		<%= f.label :username %>
		<%= f.text_field :username %>
	</div>

	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/welcome/index.html.erb
<%= link_to "Show all projects", projects_path %>
<h1>Welcome to Crowdfunder!</h1>

<%= link_to 'Make stuff happen...', "/projects/new"  %>